### ISSUE TITLE
hello "\" this Symbole does also not work 

### ISSUE THREAD

**Issue by allrightt** [BesoBerlin/Arduino-German-Keyboard#2]
hello "\" this Symbole does also not work.
Maybe you can fix it 
thank for your nice workaround :)

**Comment by BesoBerlin** [comment]
Hi! Thank you!
Did you use the script? 
Or did you use the experimental library?
As in c++ in Arduino it is necessary to declare a / (backslash) within a string with another backslash, otherwise it will think you want to declare the following character to be shown in the string. So to show or print a backslash in the string you have to write "//" (a double backslash).
So a backslash is kind of special. But that's not related to the script, it's related to the language c ...

Or did I get you wrong?

**Comment by BesoBerlin** [comment]
Please let me know if it works for you!

**Comment by BesoBerlin** [comment]
Does it?
